AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Hashing Lambda Function

Resources:
  HashingFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: lambdaRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
  hashingFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'com.lambda.LambdaApiGateway::handleRequest'
      Runtime: java17
      Description: ''
      MemorySize: 512
      Timeout: 15
      CodeUri: target/lambda-function-0.1.0-SNAPSHOT.jar
      Role: !GetAtt HashingFunctionRole.Arn
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto